apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db-user: amFzb24y
  db-pass: amFzb24y
  db-db: dXJsX3Nob3J0ZW5lcg==
  db-url: cG9zdGdyZXNxbDovL2phc29uMjpqYXNvbjJAZGItc2VydmljZTo1NDMyL3VybF9zaG9ydGVuZXI=
